bank_project/bank_app/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'bank_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('customer/', views.customer_index, name='customer'),
    path('customer_account_details/<account_pk>/', views.customer_account_details,
         name='customer_account_details'),
    path('customer_make_transfer/', views.customer_make_transfer,
         name="customer_make_transfer"),
    path('staff/', views.staff_index, name='staff'),
    path('staff_customer_details/<customer_pk>/', views.staff_customer_details,
         name='staff_customer_details')
]

bank_project/bank_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('bank/', include('bank_app.urls')),
    path('accounts/',include('login_app.urls'))
]

bank_project/login_app/urls.py
from django.urls import path
from . import views


app_name = 'login_app'

urlpatterns = [
        path('login/', views.login, name='login'),
        path('logout/', views.logout, name='logout'),
        path('sign_up/', views.sign_up, name='sign_up'),
        path('password_reset/', views.password_reset, name='password_reset'),
        path('password_reset_request/', views.password_reset_request, name='password_reset_request'),
        path('delete_account/', views.delete_account, name='delete_account'),
]

bank_project/login_app/models.py
from django.db import models
from django.contrib.auth.models import User
from secrets import token_urlsafe

class PasswordResetRequest(models.Model):
   user = models.ForeignKey(User, on_delete=models.CASCADE)
   token = models.CharField(max_length=43, default=token_urlsafe)
   created_timestamp = models.DateTimeField(auto_now_add=True)
   updated_timestamp = models.DateTimeField(auto_now=True)

   def __str__(self):
      return f'{self.user} - {self.created_timestamp} - {self.updated_timestamp} - {self.token}'

bank_project/login_app/views.py
from django.shortcuts import render, reverse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout
from django.http import HttpResponseRedirect
from . models import PasswordResetRequest

def sign_up(request):
   context = {}
   if request.method == "POST":
      password = request.POST['password']
      confirm_password = request.POST['confirm_password']
      user_name = request.POST['user']
      email = request.POST['email']
      if password == confirm_password:
            if User.objects.create_user(user_name, email, password):
               return HttpResponseRedirect(reverse('login_app:login'))
            else:
               context = {
                  'error': 'Could not create user account - please try again.'
               }
      else:
            context = {
               'error': 'Passwords did not match. Please try again.'
            }
   return render(request, 'login_app/sign_up.html', context)


def login(request):
    context = {}

    if request.method == "POST":
        user = authenticate(request, username=request.POST['user'], password=request.POST['password'])
        if user:
            dj_login(request, user)
            return HttpResponseRedirect(reverse('bank_app:index'))
        else:
            context = {
                'error': 'Bad username or password.',
            }
    return render(request, 'login_app/login.html')




def logout(request):
   dj_logout(request)
   return render(request, 'login_app/login.html')


def delete_account(request):
   pass


def password_reset_request(request):
    if request.method == "POST":
        post_user = request.POST['user']
        user = None

        if post_user:
            try:
                user = User.objects.get(username=post_user)
            except:
                print(f"Invalid password request: {post_user}")
        else:
            post_user = request.POST['email']
            try:
                user = User.objects.get(email=post_user)
            except:
                print(f"Invalid password request: {post_user}")
        if user:
            prr = PasswordResetRequest()
            prr.user = user
            prr.save()
            print(prr)
            return HttpResponseRedirect(reverse('login_app:password_reset'))
    return render(request, 'login_app/password_reset_request.html')


def password_reset(request):
    if request.method == "POST":
        post_user = request.POST['user']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        token = request.POST['token']

        if password == confirm_password:
            try:
                prr = PasswordResetRequest.objects.get(token=token)
                prr.save()
            except:
                print("Invalid reset attempt.")
                return render(request, 'login_app/password_reset.html')
            user = prr.user
            user.set_password(password)
            return HttpResponseRedirect(reverse('login_app:login'))
    return render(request, 'login_app/password_reset.html')

bank_project/login_app/templates/login_app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'login_app/login_app.css' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>{%block title%}{%endblock%}</title>
</head>

<body>

    {% block content %}
    {% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"
        integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js"
        integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc"
        crossorigin="anonymous"></script>
</body>

</html>

bank_project/login_app/templates/login_app/login.html
{% extends "login_app/base.html" %}

{% block content %}
<h1>Login</h1>
<a href="{% url 'login_app:sign_up' %}">Sign Up</a>
<hr />
<form action="{% url 'login_app:login' %}" method="POST">
   {% csrf_token %}
   <input type="text" name="user" placeholder="User Name">
   <input type="password" name="password" placeholder="Password">
   <button>Login</button>
</form>
<a href="{% url 'login_app:password_reset_request' %}">Forgot Password?</a>
<hr />
{% if error %}
{{ error }}
{% endif %}

{% endblock %}

bank_project/login_app/templates/login_app/password_reset.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Reset Password</title>
</head>
<body>
   <h1>Reset Password</h1>
   <hr />
   <form action="{% url 'login_app:password_reset' %}" method="POST">
      {% csrf_token %}
      <input type="text" name="user" placeholder="User Name">
      <input type="password" name="password" placeholder="New Password">
      <input type="password" name="confirm_password" placeholder="Repeat New Password">
      <input type="text" name="token" placeholder="Token">
      <button type="submit" >Reset</button>
   </form>
   <hr />
</body>
</html>

bank_project/login_app/templates/login_app/password_reset_request.html
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <title>Request Password Reset</title>
</head>
<body>
   <h1>Request Password Reset</h1>
   <hr />
      <form action="{% url 'login_app:password_reset_request' %}" method="POST">
            {% csrf_token %}
            <input type="text" name="user" placeholder="User Name">
            <input type="email" name="email" placeholder="Email Address">
            <button>Submit</button>
      </form>
   <hr />
</body>
</html>

bank_project/login_app/templates/login_app/sign_up.html
{% extends "login_app/base.html" %}

{% block content %}
<h1>Sign Up</h1>
<a href="{% url 'login_app:login' %}">Login</a>
<hr />
<form action="{% url 'login_app:sign_up' %}" method="POST">
   {% csrf_token %}
   <input type="text" name="user" placeholder="User Name">
   <input type="email" name="email" placeholder="Email Address">
   <input type="password" name="password" placeholder="Password">
   <input type="password" name="confirm_password" placeholder="Confirm Password">
   <button>Sign Up</button>
</form>
<hr />
{% if error %}
{{ error }}
{% endif %}

{% endblock %}